
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(1,'iPhone1','awesome * 1',600,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(2,'iPhone2','awesome * 2',601,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(3,'iPhone3','awesome * 3',602,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(4,'iPhone4','awesome * 4',603,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(5,'iPhone5','awesome * 5',604,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(6,'iPhone6','awesome * 6',605,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(7,'iPhone7','awesome * 7',606,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(8,'iPhone8','awesome * 8',607,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(9,'iPhone9','awesome * 9',608,'GBP');
INSERT INTO T_OFFER (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRICE,CURRENCY) VALUES(10,'iPhone10','awesome * 10',609,'GBP');